"""AI summaries — a built-in feature.

A one- to two-sentence brief per top-ranked story, generated by a local Ollama
model by default (keyless), with OpenAI- and Anthropic-compatible providers as
alternatives. Everything here is fail-soft: if no model is reachable, summarize()
returns None and the pipeline carries on — a scrape never fails because of AI.
"""
from __future__ import annotations

from dataclasses import dataclass

import httpx

from .config import AI

PROMPT = (
    "You are a security/tech news analyst. In ONE to TWO plain sentences, summarize "
    "why this story matters to a busy engineer. Be factual and specific; do not add "
    "preamble, markdown, or a title.\n\n"
    "Headline: {title}\nOutlets: {outlets}\nCVEs: {cves}\nContext: {summary}\n\nSummary:"
)


def build_prompt(title, outlets, cves, summary) -> str:
    return PROMPT.format(
        title=title, outlets=outlets or "n/a",
        cves=", ".join(cves) if cves else "none", summary=(summary or "")[:600],
    )


class Provider:
    name = "none"

    def generate(self, prompt: str) -> str | None:
        raise NotImplementedError


class OllamaProvider(Provider):
    name = "ollama"

    def __init__(self, cfg: AI):
        self.model, self.endpoint, self.timeout = cfg.model, cfg.endpoint.rstrip("/"), cfg.timeout

    def generate(self, prompt: str) -> str | None:
        try:
            r = httpx.post(f"{self.endpoint}/api/generate", timeout=self.timeout,
                           json={"model": self.model, "prompt": prompt, "stream": False})
            r.raise_for_status()
            return (r.json().get("response") or "").strip() or None
        except (httpx.HTTPError, ValueError):
            return None


class OpenAIProvider(Provider):
    name = "openai"

    def __init__(self, cfg: AI):
        self.model = cfg.model
        self.endpoint = (cfg.endpoint or "https://api.openai.com").rstrip("/")
        self.key, self.timeout = cfg.api_key, cfg.timeout

    def generate(self, prompt: str) -> str | None:
        if not self.key:
            return None
        try:
            r = httpx.post(f"{self.endpoint}/v1/chat/completions", timeout=self.timeout,
                           headers={"Authorization": f"Bearer {self.key}"},
                           json={"model": self.model, "messages": [{"role": "user", "content": prompt}]})
            r.raise_for_status()
            return r.json()["choices"][0]["message"]["content"].strip() or None
        except (httpx.HTTPError, ValueError, KeyError, IndexError):
            return None


class AnthropicProvider(Provider):
    name = "anthropic"

    def __init__(self, cfg: AI):
        self.model = cfg.model
        self.endpoint = (cfg.endpoint or "https://api.anthropic.com").rstrip("/")
        self.key, self.timeout = cfg.api_key, cfg.timeout

    def generate(self, prompt: str) -> str | None:
        if not self.key:
            return None
        try:
            r = httpx.post(f"{self.endpoint}/v1/messages", timeout=self.timeout,
                           headers={"x-api-key": self.key, "anthropic-version": "2023-06-01"},
                           json={"model": self.model, "max_tokens": 200,
                                 "messages": [{"role": "user", "content": prompt}]})
            r.raise_for_status()
            return r.json()["content"][0]["text"].strip() or None
        except (httpx.HTTPError, ValueError, KeyError, IndexError):
            return None


def make_provider(cfg: AI) -> Provider:
    return {"ollama": OllamaProvider, "openai": OpenAIProvider,
            "anthropic": AnthropicProvider}.get(cfg.provider, OllamaProvider)(cfg)


@dataclass
class Summarizer:
    provider: Provider

    def summarize(self, title, outlets, cves, summary) -> str | None:
        text = self.provider.generate(build_prompt(title, outlets, cves, summary))
        if not text:
            return None
        # keep it tight — one paragraph, no runaway output
        return " ".join(text.split())[:400]
